### PR TITLE
feat(literal): output literal %> with %%> close #153

### LINKED ISSUE #153: Output literal `%>` with `%%>`
The same as `<%%` that outputs literal `<%`, but at the opposite direction. I haven't found it in the lexer, so I guess it doesn't seem to work in any way.

### PR DESCRIPTION
**Pull request by roymiloh**

### CODE REVIEW

**Comment by RyanZim** [comment]
@roymiloh Looking good. You should edit https://github.com/mde/ejs/blob/master/docs/syntax.md#literal-tag to document this though.

**Comment by RyanZim** [comment]
@roymiloh ping?

**Comment by RyanZim** [comment]
@roymiloh ping?

**Comment by RyanZim** [comment]
@roymiloh Are you going to add the documentation?

**Comment by roymiloh** [comment]
@RyanZim yes, probably at the weekend.

**Comment by RyanZim** [comment]
@roymiloh ping?

**Comment by RyanZim** [comment]
@roymiloh ping?

**Comment by roymiloh** [comment]
@RyanZim, I added another commit for docs only (... please rebase), sorry for not merging before.

**Comment by RyanZim** [comment]
Ping @mde & @TimothyGu for code review.

@roymiloh I'm fine with you rebasing and force-pushing to this branch too.

**Comment by TimothyGu** [comment]
The code looks good.

**Comment by RyanZim** [comment]
Shall I resolve conflicts and merge?

**Comment by TimothyGu** [comment]
@RyanZim, yes, but please rebase before merging.

**Comment by RyanZim** [comment]
Just to clarify do you want it rebased ontop of master and/or interactively rebased into one commit?

**Comment by TimothyGu** [comment]
Both.

**Comment by RyanZim** [comment]
Not sure what I did wrong. I merged the changes into master but GitHub didn't auto-close the PR. Thanks for your help @roymiloh!

**Comment by TimothyGu** [comment]
@RyanZim, that's normal.

**Comment by roymiloh** [comment]
Actually not :) the PR marked as closed and "Merge PR" commit was added, probably manually (?), not sure why though. 
Anyway, thanks!

**Comment by RyanZim** [comment]
@roymiloh I merged the PR manually on the command line so I could rebase & resolve merge conflicts. GitHub didn't realize the PR was merged so I closed the PR manually.

**Pull request closed without merging**
