### PR TITLE
Add syntax documentation

### PR DESCRIPTION
**Pull request by TimothyGu**
Right now only an md document.

### CODE REVIEW

**Comment by mde** [comment]
THIS IS AWESOME. :)

**Comment by TimothyGu** [comment]
Glad you like it :) TBH this is for me more than for anybody else ;)

**Comment by mde** [comment]
It will be hugely useful for other people, trust me. :)

**Comment by wjordan** [comment]
I agree, having a reliable, accessible syntax document will be hugely useful for anyone using this library. Thanks so much for the fixes and improvements! :+1:

**Comment by TimothyGu** [comment]
Up.

**Comment by TimothyGu** [comment]
@mde Have you got a chance to look at this yet? I believe I addressed all the issues.

**Comment by TimothyGu** [comment]
I am going to merge this in ~3 days if nobody reviews, just to keep PRs from rotting.

**Pull request merged**
