### PR TITLE
options add 'views' item

### PR DESCRIPTION
**Pull request by cnwhy**
Include path can use ‘~/’.
In "nodejs" become easy use;

### CODE REVIEW

**Comment by mde** [comment]
Could you include some tests with this? I'm not sure exactly what the use-cases are.

**Comment by cnwhy** [comment]
```javascript
test('include ejs with relative path for views', function () {
    var file = 'test/fixtures/menu-views.ejs',
        viewsPath = path.join(__dirname, 'fixtures');
    assert.equal(ejs.render(fixture('menu-views.ejs'), {pets: users}, {filename: file, views: viewsPath}),
      fixture('menu.html'));
  });
```

The main test of the three cases:  
**1.** in the file ' test/fixtures/menu-views.ejs ', Test  `<%- include('~/*') -%>` 
```
<%- include('~/includes/menu-item-views', {
  url: '/bar'
, title: 'Bar'
}); -%>
```
**2.** in then file 'test/fixtures/includes/menu-item-views.ejs', Test '<% include ~/* %>'  
```
<li><% include ~/includes/menu/item %></li>
```
**3.** test then "views" value transfer
----------------
**Other**  
When "express" view engine setup:  
```javascript
// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.engine('ejs', require('ejs').__express);
```
In then file 'lib/ejs.js', the code is auto 'views' setup  : 
```
  //express auto 'views' option;
  if (data && data.settings ) {
    opts.views = data.settings.views;
  }
```

(Sorry, I know my English is very bad!)

**Comment by RyanZim** [comment]
I'm not in favor of this since this requires one more option to be passed to use `include()`. Also, it is rather confusing to use `~/` since that normally refers to your home directory on *nix.

CC: @mde

**Comment by RyanZim** [comment]
@mde @TimothyGu any objections to closing this? As I said, I'm not in favor of this, the PR is old, and the code causes merge conflicts.

**Comment by RyanZim** [comment]
@mde ping?

**Comment by mde** [comment]
Yes, let's close it.

**Pull request closed without merging**
