### PR TITLE
Add CNAME file to generated docs, link to ejs.co from JSDocs

### PR DESCRIPTION
**Pull request by RyanZim**
As per https://github.com/mde/ejs/issues/218.

### CODE REVIEW

**Comment by RyanZim** [comment]
Fixed an error that I had made; I was a bit tired when I wrote this.

**Comment by RyanZim** [comment]
@mde?

**Comment by RyanZim** [comment]
@mde ping?

**Comment by RyanZim** [comment]
@mde ping?

**Comment by mde** [comment]
LGTM. Sorry for the delay.

**Pull request merged**
