### PR TITLE
Don't .trim() unconditionally

### LINKED ISSUE #60: Why EJS v2 delete a line break at the end of file
I'm just curious. Why EJS v2 delete a line break at the end of file.
I might want to keep it in an original state. What do you think?

### PR DESCRIPTION
**Pull request by TimothyGu**
Fixes #60.

Q: is this a breaking change? Should we maintain compat with 2.x behavior or 1.x behavior?

### CODE REVIEW

**Comment by whitneyit** [comment]
In regards to #64 [line 264 in lib/ejs.js](https://github.com/mde/ejs/commit/d1e10292260d6836ee0e7ccb82de46c9627b86d6#diff-0d9afaa7ce3db4d8cac4ca2abf3584baL264) seems to be the only area of conflict. Changing it to

```js
      this.source += '  return __output.join("");' + '\n';
```

should resolve *that* conflict.

**Comment by TimothyGu** [comment]
@whitneyit yes.

**Comment by mde** [comment]
I remember adding the `trim` at some point to satisfy the v1 tests. I think preserving the content of the template file is a win though, so let's merge this.

**Comment by TimothyGu** [comment]
Cool.

**Pull request merged**
