### PR TITLE
Add Thinkful live help sessions badge to README

### PR DESCRIPTION
**Pull request by cmrnh**
Hi @mde — as promised, pull request to add a Thinkful badge to the README. Following up on mde/ejs-site to add a support section to http://ejs.co/ too

### CODE REVIEW

**Comment by RyanZim** [comment]
@mde, any reason not to merge this?

**Comment by RyanZim** [comment]
@mde @TimothyGu ping?

**Comment by mde** [comment]
As long as people don't think we're somehow endorsing the service, I guess it's okay -- what do you think?

**Comment by RyanZim** [comment]
@mde I don't really care; I just want this to be either merged or closed. It's all up to you.

**Comment by mde** [comment]
@cmrnh Sincerest apologies. I think I'd prefer to keep things simple, and not rely on outside third-party services.

**Pull request closed without merging**
