### PR TITLE
Test and document `escape` option

### PR DESCRIPTION
**Pull request by rpaterson**

### CODE REVIEW

**Comment by rpaterson** [comment]
I want to use EJS to generate SQL.  Happily it already has an option to customize the escape function, but it was not tested or documented.

**Comment by RyanZim** [comment]
This would partially fix #142 by documenting `escape`.

Docs look good to me; I'll leave @mde check the tests.

@mde: go ahead and merge whenever you finish checking the tests.

**Comment by RyanZim** [comment]
Docs & tests LGTM

CC: @mde @TimothyGu 
Could one of you double-check & merge this?

**Comment by RyanZim** [comment]
@mde & @TimothyGu ping?

**Comment by RyanZim** [comment]
@mde ping?

**Comment by RyanZim** [comment]
Attn: @mde @TimothyGu: To avoid code rot, I will merge this in ~7 days unless someone says otherwise.

**Comment by RyanZim** [comment]
Merging. Sorry so long @rpaterson.

**Comment by rpaterson** [comment]
No problem, thanks for merging

**Pull request merged**
