### PR TITLE
Enable Github Actions to perform automated tests

### PR DESCRIPTION
**Pull request by ayanamidev**
Also applied lint for every files

### CODE REVIEW

**Comment by ayanamidev** [comment]
Example: https://github.com/ayanamitech/ejs/actions/runs/2402421996

**Comment by mde** [comment]
I'm not sure what this PR is intended to accomplish. There is already a `.travis.yml` for CI with Travis, and there is an existing lint task in the `jakefile.js`. I appreciate the effort but this is unnecessary. I am closing this PR, but please let me know if I am missing something.

**Comment by mde** [comment]
I'm not sure what this PR is intended to accomplish. There is already a `.travis.yml` for CI with Travis, and there is an existing lint task in the `jakefile.js`. I appreciate the effort but this is unnecessary. I am closing this PR, but please let me know if I am missing something.

**Comment by ayanamidev** [comment]
@mde Because I think travis is no longer working well right now right?

**Pull request closed without merging**
