### PR TITLE
fixed some situations...

### PR DESCRIPTION
**Pull request by db-developer**
where null or undefined on 'to', 'from' or 'list' would throw exceptions.
1. Error: cant' set properties to 'null' or 'undefined' (if 'to' was 'null' or 'undefined')
2. 'from' should always exist (in 'shallowCopy' as well as in 'shallowCopyFromList')
3. Error: list.length will fail if list was 'null' or 'undefined'

### CODE REVIEW

**Comment by mde** [comment]
This is great. :) Could you add some tests for these?

**Comment by db-developer** [comment]
Uhmmm ... not sure if these would fit into your scope of testing.
You have a more application focused approach, while I did unit tests specifically on the ways 'shallowCopy' and 'shallowCopyFromList' >might< be called. In fact I don't even know if there are circumstances which result in 'list' being null...

... but yes, if you want these tests to be part of the suite I can add them.

**Comment by mde** [comment]
If you have tests, let's include them! No reason not to have more unit tests.

**Comment by db-developer** [comment]
Ok, gonna convert them for your test suite and try to find out how to change a pull request.
... I'll be back :-)

**Comment by mde** [comment]
Really appreciate it. Thanks for your hard work!

**Comment by db-developer** [comment]
... assimilate this! :)

**Comment by mde** [comment]
Whoa, this is awesome!

**Comment by mde** [comment]
Thank you, sir!

**Comment by db-developer** [comment]
You're welcome :-)

**Pull request merged**
