### PR TITLE
Fix pkg entry file for browser (compiled)

### PR DESCRIPTION
**Pull request by leomp12**
Fix to handle `import ejs from 'ejs'` within bundlers such as Webpack.

### CODE REVIEW

**Comment by mde** [comment]
Thank you!

**Comment by mde** [comment]
Heads up: I had to remove the "browser" property for Browserify to work when creating the most recent bugfix release. I haven't done the research to see how these work, but you'll need to make sure you can run the `jake package` command successfully before we can put it back.

**Comment by mde** [comment]
Also, I'm not sure the UMD module generated by Browserify is what we want to be specifying for all bundlers. This had some helpful info: https://github.com/defunctzombie/package-browser-field-spec

**Comment by leomp12** [comment]
@mde okay, I'll take a look

**Pull request merged**
