### PR TITLE
test for include in expression or escaped

### PR DESCRIPTION
**Pull request by User4martin**
test for include used in escape or in expression
as requested in #285

### CODE REVIEW

**Comment by mde** [comment]
Excellent, thank you!

**Comment by mde** [comment]
Also, @User4martin, have given you the commit bit. :) Let's continue to use PRs where possible, but you're doing great work here.

**Comment by User4martin** [comment]
thanks for the commit bit. appreciated. no worries, I am fine with PR

**Comment by mde** [comment]
You are doing awesome work! It's really appreciated. :)

**Comment by RyanZim** [comment]
Congratulations @User4martin :tada: Welcome to the EJS team!

**Pull request merged**
