### PR TITLE
Factor out require('path')

### PR DESCRIPTION
**Pull request by zensh**

### CODE REVIEW

**Comment by TimothyGu** [comment]
I don't see a reason for this anyway, but as it kind of shortens the code, merged, thanks.

**Comment by mde** [comment]
Good call. I had originally left this inside the call because I wasn't yet sure how I was going to package it for browser use.

**Comment by TimothyGu** [comment]
@mde oh oops just saw your comments now.

**Comment by mde** [comment]
No worries. :) It's fine since we ended up going with Browserify. We might want to look further for something more universal (e.g., UMD-ish) in the longer-term though.

**Comment by TimothyGu** [comment]
@mde Yep, just double checked. Browserify handles `require('path')` correctly.

**Comment by mde** [comment]
:+1:

**Pull request merged**
